"use client";
// don`t use use client in main layout.js;
import Link from "next/link";
import "./global.css";
import { usePathname } from "next/navigation";
// export const metadata = {
//   title: "Next.js",
//   description: "Generated by Next.js",
// };

export default function RootLayout({ children }) {
  const pathName = usePathname(); // to active a path
  return (
    <html lang="en">
      <body>
        {children}
        {/* userList link don`t show */}
        {pathName !== "/userList" ? (
          <ul className="mt-6 font-bold text-green-400 ml-8">
            {/* Link route */}
            <li>
              <Link
                href="/"
                className={`${pathName === "/" ? "text-red-500" : ""}`}
              >
                Home
              </Link>
            </li>
            <li>
              <Link
                href="/about"
                className={`${pathName === "/about" ? "text-red-500" : ""}`}
              >
                About
              </Link>
            </li>
            <li>
              <Link
                href="/userList"
                className={`${pathName === "/userList" ? "text-red-500" : ""}`}
              >
                UserList
              </Link>
            </li>
            <li>
              <Link
                href="/login"
                className={`${pathName === "/login" ? "text-red-500" : ""}`}
              >
                Login
              </Link>
            </li>
            <li>SignUp</li>
          </ul>
        ) : (
          <Link href="/">Go home</Link>
        )}
        {/* we can use null  */}
      </body>
    </html>
  );
}
